### ISSUE TITLE
Slight issue with append ie '>'

### ISSUE THREAD

**Issue by enricribas** [JsonHunt/save-commands#12]
In Rails, I'd like to do the following
"config/routes.rb : rake routes > routes.txt"

so that it creates a routes.txt file every time I change the routes file. (saves time referencing it)

Unfortunately I get this error 
Don't know how to build task '>' 

Thanks.

**Comment by cperryk** [comment]
Think this is related to this issue I just posted: https://github.com/JsonHunt/save-commands/issues/14

Seems like save-commands doesn't recognize carrots or pipes.

**Comment by bungle** [comment]
Also `&&` doesn't work, e.g.:

``` json
commands: [
      "/usr/local/etc/nginx.conf: /usr/local/bin/nginx -t && /usr/local/bin/nginx -s reload"
]
```

**Comment by JsonHunt** [comment]
replaced win-spawn with cross-spawn-async. That should fix the problem
