### ISSUE TITLE
The sample config.cson doesn't work.

### ISSUE THREAD

**Issue by QinMing** [JsonHunt/save-commands#13]
The sample `config.cson` in readme doesn't work. Only the following works for me.

```
  "save-commands":
    commands: [
      "**/*.go : goimports -w {relPath}{filename}"
    ]
```

The important point is that I need to use `commands` as key, but not `saveCommands`

**Comment by danielo515** [comment]
Not only fix the readme, also fix the implementation because the package saves the configuration with that parameters

**Comment by JsonHunt** [comment]
fixed
