### ISSUE TITLE
Carrots and pipes don't work

### ISSUE THREAD

**Issue by cperryk** [JsonHunt/save-commands#14]
Set up this in the config:

```
 "**/*.cson : echo 'foo' > bar.txt"
```

On save, the console returns:

```
'foo' > bar.txt
```

And no `bar.txt` is created.

**Comment by JsonHunt** [comment]
I replaced win-spawn with cross-spawn-async. That should fix the problem

**Comment by pwang2** [comment]
seems still not working.  any updates?
