### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by gsklee** [JsonHunt/save-commands#22]
Package is not working at all with Atom 1.0.11

**Comment by andykais** [comment]
I agree with this statement. I am also running 1.0.11 and I have this `save-commands.json` file in my project directory

```
{
    "timeout": 4000,
    "commands": [
         "*.tex : touch {relPath}/test.txt"
    ]
}
```

I have no `"save-commands"` in config.cson, is it necessary? I can see the `Run batch save-commands` option in my right click menu but that also does nothing

**Comment by jacobrs** [comment]
On 1.0.13 it doesn't seem to work either. @andykais I have the same type of setup where I run without a cson file. I'll try to add that and check if it fixes the issue. My `save-commands.json` consists of this

```
{
    "timeout": 4000,
    "commands": [
        "** : /Users/jacob/csbin/pts"
    ]
}
```

Where pts is loaded in my path variables and is suppose to run as a script, standard bash stuff. I get the issue #24

**Comment by andykais** [comment]
could you tell me where you got that error message in [#24](https://github.com/JsonHunt/save-commands/issues/24)? Just some output to affirm save-commands is doing something would be helpful

**Comment by jacobrs** [comment]
I get the error every time I try to save a file in that project. save-commands seems to be trying to do something, but it runs into an error before it really does anything.

**Comment by jacobrs** [comment]
Ended up fixing the error by modifying the `lib/atom-save-commands.coffee` script. Left more details in issue #24

**Comment by JsonHunt** [comment]
fixed
