### ISSUE TITLE
Error message: "'elm' could not be spawned"

### ISSUE THREAD

**Issue by donbarthel** [JsonHunt/save-commands#27]
Atom 1.3.2 running on Ubuntu 14.04 LTS.

This other project had (and fixed) a very similar issue: https://github.com/wende/autocomplete-erlang/issues/3

Workaround for now is start Atom from command line, not from desktop.

**Comment by JsonHunt** [comment]
check the latest version and let me know if you still have this issue. If so, please provide more details. Thanks!

**Comment by donbarthel** [comment]
I tried just now to recreate the problem but I forget how to use your addin. I re-read https://github.com/JsonHunt/save-commands and the command is in the right click menu but it doesn't seem to activate. The instructions aren't clear in my mind. Unless I can get the original to do something again then testing with the new version will be inconclusive.

**Comment by JsonHunt** [comment]
I removed the right click menu from the latest version. Closing the issue for now

**Comment by TheOddler** [comment]
I'm having the same problem. But can't figure out how it's been fixed. Could you explain a bit more?
