### ISSUE TITLE
Red error when there is no .json

### ISSUE THREAD

**Issue by katsar0v** [JsonHunt/save-commands#42]
This is really nasty that I get an red error screen when I have no config file in my project or the dir I am currently working on. Isn't there a way to fix that and show no error when there is no config and just do nothing?

**Comment by mvila** [comment]
Since this repository has been abandoned by his author, I created a plugin doing the same thing with a simpler interface: https://github.com/mvila/on-save

**Comment by JsonHunt** [comment]
This is now resolved
