### ISSUE TITLE
Unable to resize or close pane

### ISSUE THREAD

**Issue by jeffmagill** [JsonHunt/save-commands#45]
Once the output pane is opened, I am unable to resize or close it. It takes up about 25% of my screen real estate so this a poor experience for me. When I resize the Atom window, the output pane remains the same size and the text editor shrinks. That basically means I can only work in Atom full sized.

Please consider granting the ability to resize and close that pane. ***I think*** this means converting it to a Panel. I briefly looked into this and since I dont know the API at all, I dont have the time to figure this out myself.

https://atom.io/docs/api/v1.0.0/Panel

**Comment by jeffmagill** [comment]
I realized that <kbd>Esc</kbd> will close the window as a workaround. I still think this should have a more configurable user experience. I dont need the window to be so big. I dont necessarily want it to pop up every time I save (I hit <kbd>Cmd</kbd> + <kbd>S</kbd> quite a bit) It would be nice to change the position.

**Comment by Mario-Duarte** [comment]
This seams to be the only package that runs commands on save for wind and mac, have used other but only work on mac the downside of this one is like you said, can't resize the output pane or even close it...Thanks for the tip on the ESC key.

Would be really cool if this was an actual panel...i might look into doing this
