### ISSUE TITLE
apm install save-commands@<previous-version> doesn't work

### ISSUE THREAD

**Issue by petemill** [JsonHunt/save-commands#5]
Because of the error with 0.5.0, I am trying to install the previous version 0.4.0 as found at https://github.com/JsonHunt/save-commands/releases but it seems that APM does not know about it:

```
› apm install save-commands@0.4.0
Installing save-commands@0.4.0 to /Users/petemill/.atom/packages ✗
Package version: 0.4.0 not found
```

**Comment by JsonHunt** [comment]
Not sure what to do about previous version, but new version is out now.
